export const usersDummy = {
  "user1": { name: "김개발", profileImage: "https://i.pravatar.cc/150?img=3" },
  "user2": { name: "이프론", profileImage: "https://i.pravatar.cc/150?img=12" },
  "user3": { name: "박디자", profileImage: "https://i.pravatar.cc/150?img=5" },
  "user4": { name: "최개발", profileImage: "https://i.pravatar.cc/150?img=8" },
  "system": { name: "System", profileImage: null },
};

export const notificationsDummy = [
  {
    id: 1,
    type: "message",
    userId: "user1",
    action: "메시지를 보냈습니다.",
    target: "스마트 블록 조립 앱",
    time: "5분 전",
    isRead: false,
  },
  {
    id: 2,
    type: "apply",
    userId: "user2",
    action: "포지션에 지원했습니다.",
    target: "장난감 거래 플랫폼",
    role: "프론트엔드 개발자",
    time: "1시간 전",
    isRead: false,
  },
  {
    id: 3,
    type: "like",
    userId: "user3",
    action: "프로젝트를 좋아합니다.",
    target: "교육용 코딩 로봇",
    time: "2시간 전",
    isRead: false,
  },
  {
    id: 4,
    type: "system",
    userId: "system",
    action: "새로운 커밋이 푸시되었습니다.",
    target: "스마트 블록 조립 앱",
    time: "3시간 전",
    isRead: true,
  },
  {
    id: 5,
    type: "interest",
    userId: "user4",
    action: "프로젝트에 관심을 표현했습니다.",
    target: "놀이터 안전 모니터링",
    time: "1일 전",
    isRead: true,
  },
  {
    id: 6,
    type: "approve",
    userId: "system",
    action: "지원이 승인되었습니다.",
    target: "장난감 리뷰 커뮤니티",
    role: "UI/UX 디자이너",
    time: "2일 전",
    isRead: true,
  }
];
